Rewards by epoch
figment-networks/near-indexer pull request #16
Opened 2021-05-13 21:37 UTC by eesmerdag

2021-05-15 00:00 UTC, eesmerdag commented
@sosedoff i will focus on historical reward_fee_fraction once again with fresh mind. it does not seem we are able to reach them now.

2021-05-15 00:06 UTC, sosedoff commented on pipeline/task_parser.go
> +				rew := new(big.Int)
you can probably move the whole calculation under https://github.com/figment-networks/near-indexer/blob/master/model/util/calculate.go if that works

2021-05-15 00:06 UTC, sosedoff commented on store/queries/validators_rewards_monthly.sql
> +	to_char(last_time, 'YYYY-MM') AS month,
What if i want to do weekly reward? Seems like using date format `YYYY-MM-DD` would work. In case if we want to do that, we can use a `time-bucket` pattern, ie you include `bucket` - `month/day/weed` (month/day/week)` and a corresponding date. 

Examples:

```
SELECT DATE_TRUNC('month', NOW()) # 2021-05-01T00:00:00-05:00
SELECT DATE_TRUNC('day', NOW())   # 2021-05-14T00:00:00-05:00
SELECT DATE_TRUNC('week', NOW())  # 2021-05-10T00:00:00-05:00
```

If that's not the case, we can use the full month date format `DATE_TRUNC('month', NOW())` to be consistent.

2021-05-15 00:26 UTC, pacmessica reviewed
not a bad start, but still needs more steps for delegators. Are you planning on adding those to a different PR?

2021-05-15 00:26 UTC, pacmessica commented on store/validator_aggs.go
> +func (s *ValidatorAggsStore) CalculateRewards(account string, from time.Time, to time.Time) (model.RewardsResponse, error) {
`CalculateRewards` name doesn't really fit - you're not calculating, you're fetching/getting, no?

2021-05-15 00:26 UTC, pacmessica commented on pipeline/task_parser.go
> +				reward.Quo(reward, big.NewInt(int64(fee.Denominator)))
wondering how you came up with this calculation, can you explain / point to documentation?

2021-05-15 00:26 UTC, pacmessica commented on server/server.go
> +	router.GET("/validators/:id/rewards", s. GetValidatorRewards)
I don't think this route is necessary. The goal is to fetch rewards for delegators. And from what I've seen, the rewards for a validator are likely a reward pool (show me if I'm mistaken- I don't really know what you calculated above).

end goal is probably `"/accounts/:id/rewards"`, this validator route won't be used

2021-05-17 12:48 UTC, eesmerdag commented on model/types/query_params.go
> +type QueryParams struct {
👍

2021-05-17 12:51 UTC, eesmerdag commented on model/rewards.go
> +type RewardsResponse struct {
👍

2021-05-17 12:55 UTC, eesmerdag commented on model/validator.go
> +	Reward         types.Amount `json:"reward"`
that is true.

2021-05-17 13:09 UTC, eesmerdag commented on pipeline/task_parser.go
> +				rew := new(big.Int)
👍

2021-05-17 14:32 UTC, eesmerdag commented on store/queries/validators_rewards_monthly.sql
> +	to_char(last_time, 'YYYY-MM') AS month,
👍

2021-05-17 17:07 UTC, eesmerdag commented on store/validator_aggs.go
> +func (s *ValidatorAggsStore) CalculateRewards(account string, from time.Time, to time.Time) (model.RewardsResponse, error) {
changed to FetchRewardsByInterval 👍

2021-05-17 23:32 UTC, pacmessica reviewed
looks promising! So when you run this, does the response make sense? what kind of reward amounts/rates do you get and how do they compare to reward rates near promises?

2021-05-18 13:03 UTC, eesmerdag commented
> looks promising! So when you run this, does the response make sense? what kind of reward amounts/rates do you get and how do they compare to reward rates near promises?

I need to confirm the results from somewhere at https://near-overview.genesislab.net/validators/. i will let you know

2021-05-18 13:12 UTC, eesmerdag commented on model/util/calculate.go
> +	"github.com/figment-networks/near-indexer/model"
👍

2021-05-18 13:52 UTC, eesmerdag commented on model/util/calculate.go
> +func CalculateDelegatorReward(delegation near.Delegation, validator *model.Validator, remainingRewards types.Amount) (types.Amount, error) {
👍

2021-05-18 16:09 UTC, eesmerdag commented on pipeline/task_parser.go
> +				reward.Quo(reward, big.NewInt(int64(fee.Denominator)))
https://github.com/near/core-contracts/blob/d84f7a924b79009d3f7aa4e577c07b08a0489dc9/staking-pool/src/internal.rs#L194 this is the main function.

2021-05-18 16:09 UTC, eesmerdag commented on server/server.go
> +	router.GET("/validators/:id/rewards", s. GetValidatorRewards)
i prefer to have different endpoints for validators and delegators. is it fine?

2021-05-18 17:38 UTC, eesmerdag commented
> > looks promising! So when you run this, does the response make sense? what kind of reward amounts/rates do you get and how do they compare to reward rates near promises?
> 
> I need to confirm the results from somewhere at https://near-overview.genesislab.net/validators/. i will let you know

@pacmessica 
how i tested?

what i have:
1. this page, which is from near network, shows the current epoch. one epoch is about 12 hours in this network.
2. https://near--indexer.datahub.figment.io/apikey/APIKEY/epochs returns the epochs.

so the only case i could test was fetching delegators info from the previous epoch and see staked_balance and calculating rewards(done by this code). and then summing these two should give the staked balance at current epoch for that delegator. but in this case, i suppose no withdraws etc.

2021-05-19 20:38 UTC, pacmessica requested changes
So overall looks good. Feels like the code integrates well into the repo (sometimes you add things and they stick out like a sore thumb), so nice job there. And looks to me like we're doing the right calculations. I have a few questions and suggestions after going through this in more detail, otherwise I think it's ready

2021-05-19 20:38 UTC, pacmessica commented on pipeline/task_fetcher.go
> +			continue
why are you ignoring these errors? Are they expected? I feel like we should at least log them, no?

2021-05-19 20:38 UTC, pacmessica commented on server/params.go
> +	ValidatorId string `form:"validator_id" binding:"required" `
this should be optional. So if no validator id is provided, then it fetches rewards for all validators (sum up reward amounts per validator per time interval is how it's been implemented in other networks).

You could also make this more flexible- rather than a single id, it could accept multiple ids- but that's I think a nice to have

2021-05-20 13:17 UTC, eesmerdag commented on model/util/calculate.go
> +	reward, _ := new(big.Int).SetString(validator.Stake.String(), 10)
👍

2021-05-20 13:46 UTC, eesmerdag commented on pipeline/task_fetcher.go
> +			continue
i head problems while fetching delegations for some validators. i just checked again, this should be changed, thanks for the catch

2021-05-20 14:06 UTC, eesmerdag commented on server/params.go
> +	ValidatorId string `form:"validator_id" binding:"required" `
👍

2021-05-20 15:58 UTC, sosedoff commented on model/util/calculate.go
> +	reward.Div(reward, big.NewInt(int64(rewardFeeFraction.Denominator)))
commission sounds right, although we already use the term `RewardFee` that represents their commission rate (in %). My guess is that we want to continue using this term, ie `Reward` - is the total commission earned by a validator in the epoch, `RewardFee` indicates the cut.

2021-05-27 14:46 UTC, pacmessica approved these changes
lgtm

2021-05-27 17:15 UTC, sosedoff commented on server/server.go
> +		badRequest(c, errors.New("invalid from or/and to date or missing interval or validator id"))
we should use the `Validate() -> error` method to return the exact errors instead of let users guess what is wrong with the request, see `statsParams` struct for an example

2021-06-21 18:56 UTC, merged