track historical delegators sync
figment-networks/near-indexer pull request #32
Opened 2021-06-30 21:58 UTC by eesmerdag

2021-07-02 17:27 UTC, eesmerdag commented
I think we can create a version for this one for one time and after fetching we can use endpoint.

2021-07-05 17:15 UTC, eesmerdag commented
this should be released after step 1 is on prod

2021-07-12 15:57 UTC, pacmessica commented on store/queries/un_indexed_delegators_epochs.sql
> +ORDER BY start_height DESC
So the point of this method is to return all epochs that come before the first delegator_epoch indexed in db right? It assumes all epochs are indexed, but that we only started indexing delegator_epochs sometime afterwards?

If yes, I think it could be clearer to break it into two methods rather than use a single query with join. 

eg `(s DelegatorEpochsStore) First(limit int) ([]delegatorEpoch, error)`, then `(s EpochsStore) FindAll(start, end int64) ([]model.Epoch, error)` and then paginating through the results from FindAll so that you can query in batches as part of `RunSyncHistoricalDelegators` rather then fetch all the records at once (because I imagine that list could be very very big).

what do you think?

2021-07-13 19:14 UTC, eesmerdag commented on store/validator_aggs.go
> +func (s ValidatorAggsStore) FindValidatorsByEpoch(epoch string) ([]model.ValidatorEpoch, error) {
👍

2021-07-13 19:15 UTC, eesmerdag commented on store/queries/un_indexed_delegators_epochs.sql
> +ORDER BY start_height DESC
hmmm lets leave it as it is now. we won't need this code at all after sync

2021-07-13 19:32 UTC, eesmerdag commented on pipeline/run_sync.go
> +	epochs, err := db.Epochs.FindUnIndexedDelegatorsEpochs()
👍

2021-07-13 20:32 UTC, pacmessica commented on store/queries/un_indexed_delegators_epochs.sql
> +ORDER BY start_height DESC
ok, so if you want to keep this, I checked a few things cause I was still concerned about the number of records being returned. Query takes ~1min and returns 700 records, so I think it's fine since we're just running this once.

```
defaultdb=> explain analyze SELECT
defaultdb->    id,
defaultdb->    start_height,
defaultdb->    start_time,
defaultdb->    end_height,
defaultdb->    end_time,
defaultdb->    blocks_count,
defaultdb->    validators_count,
defaultdb->    average_efficiency
defaultdb->  FROM epochs
defaultdb->  WHERE start_height < (SELECT start_height FROM epochs
defaultdb(>                        INNER JOIN delegator_epochs ON epochs.ID = delegator_epochs.EPOCH
defaultdb(>                        ORDER BY start_height ASC LIMIT 1)
defaultdb->  ORDER BY start_height DESC;
                                                                                        QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Index Scan Backward using idx_epochs_start_height on epochs  (cost=7.28..34.69 rows=252 width=82) (actual time=65263.815..65264.153 rows=713 loops=1)
   Index Cond: (start_height < $1)
   InitPlan 1 (returns $1)
     ->  Limit  (cost=0.83..7.00 rows=1 width=4) (actual time=65263.298..65263.302 rows=1 loops=1)
           ->  Nested Loop  (cost=0.83..3523280.73 rows=570180 width=4) (actual time=65263.297..65263.300 rows=1 loops=1)
                 ->  Index Scan using idx_epochs_start_height on epochs epochs_1  (cost=0.28..45.63 rows=757 width=48) (actual time=0.042..8.015 rows=714 loops=1)
                 ->  Index Only Scan using idx_delegator_epochs_account_epoch on delegator_epochs  (cost=0.55..4486.51 rows=16770 width=44) (actual time=91.384..91.384 rows=0 loops=714)
                       Index Cond: (epoch = epochs_1.id)
                       Heap Fetches: 1
 Planning Time: 6.613 ms
 Execution Time: 65264.265 ms
(11 rows)
```

2021-07-13 20:34 UTC, pacmessica commented on store/queries/unindexed_delegators_epochs.sql
> +                      INNER JOIN delegator_epochs ON epochs.ID = delegator_epochs.EPOCH
```suggestion
                      INNER JOIN delegator_epochs ON epochs.id = delegator_epochs.epoch
```

2021-07-13 20:46 UTC, pacmessica commented on store/queries/un_indexed_delegators_epochs.sql
> +ORDER BY start_height DESC
should also remove code after sync then

2021-07-13 20:53 UTC, eesmerdag commented on store/queries/un_indexed_delegators_epochs.sql
> +ORDER BY start_height DESC
yes there will be about 700 epochs and I think this will take 5 6 days to fetch all

2021-07-13 20:53 UTC, eesmerdag commented on store/queries/un_indexed_delegators_epochs.sql
> +ORDER BY start_height DESC
we can remove the code after sync

2021-07-14 01:57 UTC, sosedoff requested changes
First CR round is in

2021-07-14 01:57 UTC, sosedoff commented on cli/sync.go
> +	err = pipeline.RunSyncHistoricalDelegators(cfg, db, clients)
RunSyncHistoricalDelegators method is loading a new logger instance via `logrus.StandardLogger()`, though we need to pass it down since we already have access to it in `runSyncHistoricalDelegators`.

2021-07-14 01:57 UTC, sosedoff commented on pipeline/run_sync.go
> +	logger.Info(" number of epochs for sync: ", len(epochs))
Can you format the message a bit? We're using a structured logger, so using a field tag would be best: `logger.WithField("count", len(epochs)).Info("found historical epochs to sync")`

2021-07-14 01:57 UTC, sosedoff commented on pipeline/run_sync.go
> +	var err error
error var is unnecessary

2021-07-14 01:57 UTC, sosedoff commented on pipeline/run_sync.go
> +	for _, e := range epochs {
prefer `epoch` over `e`

2021-07-14 01:57 UTC, sosedoff commented on pipeline/run_sync.go
> +		logger.WithField("epoch", e.ID).Info(" fetching historical delegators")
remove empty space in the log message

2021-07-14 01:57 UTC, sosedoff commented on pipeline/run_sync.go
> +				fetcherTask.logger.WithError(err).Error(fmt.Sprintf("can not fetch delegations, validator_id %s retrying from another node", account))
use structured logging

2021-07-14 01:57 UTC, sosedoff commented on pipeline/run_sync.go
> +				fetcherTask.logger.WithError(res.err).Error(fmt.Sprintf("can not fetch delegations, validator_id %s ", res.account))
use structured logging

2021-07-14 01:57 UTC, sosedoff commented on store/queries/unindexed_delegators_epochs.sql
> +WHERE start_height < (SELECT start_height FROM epochs
try to use even nested formatting:

```
FROM
  epochs
WHERE
  start_height < (
    SELECT start_height FROM epochs
    INNER JOIN delegator_epochs ON epochs.ID = delegator_epochs.epoch
  )
```

2021-07-14 13:26 UTC, eesmerdag commented on pipeline/run_sync.go
> +	var err error
👍

2021-07-14 13:27 UTC, eesmerdag commented on pipeline/run_sync.go
> +	for _, e := range epochs {
👍

2021-07-14 13:27 UTC, eesmerdag commented on pipeline/run_sync.go
> +		logger.WithField("epoch", e.ID).Info(" fetching historical delegators")
👍

2021-07-14 13:29 UTC, eesmerdag commented on store/queries/unindexed_delegators_epochs.sql
> +                      INNER JOIN delegator_epochs ON epochs.ID = delegator_epochs.EPOCH
👍

2021-07-14 13:40 UTC, eesmerdag commented on store/queries/unindexed_delegators_epochs.sql
> +WHERE start_height < (SELECT start_height FROM epochs
👍

2021-07-14 13:44 UTC, eesmerdag commented on cli/sync.go
> +	err = pipeline.RunSyncHistoricalDelegators(cfg, db, clients)
👍

2021-07-14 13:50 UTC, eesmerdag commented on pipeline/run_sync.go
> +				fetcherTask.logger.WithError(err).Error(fmt.Sprintf("can not fetch delegations, validator_id %s retrying from another node", account))
👍

2021-07-14 13:54 UTC, eesmerdag commented on pipeline/run_sync.go
> +				fetcherTask.logger.WithError(res.err).Error(fmt.Sprintf("can not fetch delegations, validator_id %s ", res.account))
👍

2021-07-14 14:18 UTC, pacmessica approved these changes
lgtm, just removed another space from your log

2021-07-14 14:18 UTC, pacmessica commented on pipeline/run_sync.go
> +	logger.Info(" finishing fetching historical delegators")
```suggestion
	logger.Info("finishing fetching historical delegators")
```

2021-07-15 01:38 UTC, sosedoff commented on store/queries/unindexed_delegators_epochs.sql
> +WHERE start_height < (SELECT start_height FROM epochs
eh good enough, we can always fix the formatting later

2021-07-15 01:39 UTC, merged