rewards endpoint changes
figment-networks/near-indexer pull request #36
Opened 2021-07-12 21:10 UTC by eesmerdag

2021-07-12 21:41 UTC, sosedoff requested changes
Looking good so far - i left a few comments, would be great if we're not building SQL by hand.

2021-07-12 21:41 UTC, sosedoff commented on store/delegators.go
> +	if account != "" {
I would prefer if we are not building the full query via string concatenation. You can use gorm for this pretty easily (similar to how we use scopes in other places).

2021-07-12 21:41 UTC, sosedoff commented on server/params.go
> +	From     time.Time `form:"from" binding:"-" time_format:"2006-01-02"`
dont think you need `binding:"-"` here at all.

2021-07-13 14:10 UTC, eesmerdag commented on store/delegators.go
> +	if account != "" {
👍

2021-07-13 14:50 UTC, sosedoff commented on store/delegators.go
> +	slt = strings.Replace(slt, "$INTERVAL", "'"+timeInterval.String()+"'", -1)
i was hoping we can use named arguments: https://gorm.io/docs/sql_builder.html#Named-Argument - does not seem to be working, maybe its only supported by the newer versions of gorm?

2021-07-13 16:21 UTC, merged